import type { Metadata } from "next";
import { Lobster, Open_Sans, Slackey } from "next/font/google";
import "./globals.css";

const lobster = Lobster({
  variable: "--font-lobster",
  weight: "400",
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  weight: "400",
});

const slackey = Slackey({
  variable: "--font-slackey",
  weight: "400",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lobster.variable} ${openSans.variable} ${slackey.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
