# Local dev compose

services:
  web-ui:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - py_backend
    environment:
      BACKEND_URL: http://py_backend:8000
      NEXT_PUBLIC_API_URL: http://localhost:8000
    volumes:
      - ./web-ui:/app
      - /app/node_modules

  py_backend:
    build:
      context: ./py_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./py_backend:/app